DOCS = [
    {'id': 'd01', 'source': 'kb/windows-errors.md', 'text': 'Error code 0x80070005 means access denied. Run the installer as administrator or fix the folder permissions.'},
    {'id': 'd02', 'source': 'kb/windows-errors.md', 'text': 'Error code 0x80070057 means one of the parameters is invalid. Check the path and the settings you passed in.'},
    {'id': 'd03', 'source': 'catalog/pumps.md', 'text': 'Part #AB-9128 is the hydraulic pump seal kit for the HX series. It ships with two O-rings and one gasket.'},
    {'id': 'd04', 'source': 'catalog/pumps.md', 'text': 'Part #AB-9127 is the pump housing gasket for the LX series. It is sold separately.'},
    {'id': 'd05', 'source': 'help/accounts.md', 'text': 'To reset your password, open the login page and choose Forgot password. We email you a reset link that works for 15 minutes.'},
    {'id': 'd06', 'source': 'help/accounts.md', 'text': 'If you lost access to your email address, contact support with a photo ID so we can verify you.'},
    {'id': 'd07', 'source': 'finance/invoices.md', 'text': 'Invoice INV-2026-00431 is payable within 30 days. Late payments add a two percent monthly fee.'},
    {'id': 'd08', 'source': 'finance/refunds.md', 'text': 'You can ask for a refund within 14 days of purchase. Refunds go back to the original payment method.'},
    {'id': 'd09', 'source': 'api/errors.md', 'text': 'HTTP 429 means too many requests. Slow down and retry with exponential backoff.'},
    {'id': 'd10', 'source': 'api/errors.md', 'text': 'HTTP 503 means the service is unavailable because the server is overloaded. Try again in a minute.'},
    {'id': 'd11', 'source': 'help/laptops.md', 'text': 'If your laptop battery drains fast, lower the screen brightness and close background apps.'},
    {'id': 'd12', 'source': 'help/network.md', 'text': 'If your Wi-Fi keeps disconnecting, update the network driver and switch to a less crowded channel.'},
    {'id': 'd13', 'source': 'help/billing.md', 'text': 'To cancel your subscription, open Settings, choose Billing, and press Cancel plan.'},
    {'id': 'd14', 'source': 'catalog/keyboards.md', 'text': 'SKU KB-4471 is a mechanical keyboard with a two year warranty.'},
    {'id': 'd15', 'source': 'dev/docker.md', 'text': 'Error ECONNREFUSED 127.0.0.1:5432 means nothing is listening on port 5432. Start your Postgres container first.'},
    {'id': 'd16', 'source': 'dev/postgres.md', 'text': 'If PostgreSQL refuses connections, check that the database service is running and the port is open.'},
    {'id': 'd17', 'source': 'hr/leave.md', 'text': 'Every employee gets 24 days of paid leave each year.'},
    {'id': 'd18', 'source': 'hr/leave.md', 'text': 'Unused vacation can be carried over to next year, up to 5 days.'},
    {'id': 'd19', 'source': 'dev/kubernetes.md', 'text': 'CrashLoopBackOff means the container starts, crashes, and Kubernetes keeps trying again. Read the logs with kubectl logs.'},
    {'id': 'd20', 'source': 'help/security.md', 'text': 'If you lost your phone, sign in with a backup code and set up two factor authentication again.'},
]